homework5: iofunctions.o driver.o
	gcc -o homework5 iofunctions.o driver.o

iofunctions.o: iofunctions.c
	gcc -ansi -pedantic-errors -Wall -c iofunctions.c

driver.o: driver.c
	gcc -ansi -pedantic-errors -Wall -c driver.c


